name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.1.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  json_annotation: ^4.9.0
  retrofit: ^4.9.1
  retrofit_generator: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.2
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cast/
    - .env
